version: "3.9"

services:
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port ${PORT} --reload
    container_name: mlog-lite-api
    ports:
      - "${HOST_PORT}:${PORT}"
    env_file: ../.env.local
    volumes:
      - ..:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mlog-lite-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: